export enum ErrorCode {
  // Venue
  NO_VENUES_FOUND = 'NO_VENUES_FOUND',
  VENUE_NOT_FOUND = 'VENUE_NOT_FOUND',

  // Offers
  NO_OFFERS_AVAILABLE = 'NO_OFFERS_AVAILABLE',
  OFFER_NOT_FOUND = 'OFFER_NOT_FOUND',
  OFFER_EXPIRED = 'OFFER_EXPIRED',
  ALREADY_REDEEMED = 'ALREADY_REDEEMED',
  MAX_REDEMPTIONS_REACHED = 'MAX_REDEMPTIONS_REACHED',
  OFFER_NOT_VALID_TODAY = 'OFFER_NOT_VALID_TODAY',
  OFFER_NOT_VALID_NOW = 'OFFER_NOT_VALID_NOW',

  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',

  // Business
  VENUE_NOT_OWNED = 'VENUE_NOT_OWNED',
  OFFER_LIMIT_REACHED = 'OFFER_LIMIT_REACHED',
  INVALID_SCHEDULE = 'INVALID_SCHEDULE',
  VENUE_OFFLINE = 'VENUE_OFFLINE',

  // General
  INVALID_FILTER = 'INVALID_FILTER',
  SERVER_ERROR = 'SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
}
